### ISSUE TITLE
🐞 - [v4] `Hint` with appearance `dark` doesn't adapt to dark mode

### ISSUE THREAD

**Issue by hakimio** [taiga-family/taiga-ui#9091] opened 2024-09-19 11:26 UTC
### Code Example URL

https://taiga-ui.dev/directives/hint/API?tuiHintAppearance=dark&darkMode=true

### Description

In `v3` hint with mode on `onDark` would correctly change background color when application is switched to dark mode:

![image](https://github.com/user-attachments/assets/da021b29-27f0-4e6b-8733-198d7e3b599e)

Unfortunately this does not happen in `v4`:

![image](https://github.com/user-attachments/assets/ba09f7e4-8ed0-4364-aa09-f6d7de13981e)

----

As as sidenote, if you try to type in the demo input in dark mode, input text is not visible.

### Taiga UI version

4.7.0

### Browser Used

Chrome

### OS Used

Windows

**Comment by waterplea** [comment] 2024-09-19 11:39
You want it to be dark? It is meant to be white by design. If it was dark in v3 it is a bug

**Comment by hakimio** [comment] 2024-09-19 11:45
Yes, I do. It looks out of place in dark mode when everything else is dark and tooltip is light.
As a middle ground it could follow the same design like the new `card` component: dark grey background in dark mode.

**Comment by waterplea** [comment] 2024-09-19 11:51
I don't see the switch to dark mode for that link but latest Angular Material does exactly what we do :)

![image](https://github.com/user-attachments/assets/98e1da05-0b7e-46b0-a521-0041af275841)
![image](https://github.com/user-attachments/assets/11f7127d-cf93-4833-ae27-bc89e4cc134a)

**Comment by hakimio** [comment] 2024-09-19 11:54
You can switch the theme to dark. Here is how the tooltip looks for me in dark mode:

![image](https://github.com/user-attachments/assets/1221df22-57dc-4f0a-b13f-ca8bff26748c)

I wouldn't call it exactly what you do.

**Comment by hakimio** [comment] 2024-09-19 11:56
Ok, sorry. I was looking at the old version of Angular Material. Still I prefer the old behavior.

**Comment by waterplea** [comment] 2024-09-19 12:21
Anyway, I'll close this in favor of https://github.com/taiga-family/taiga-ui/issues/8946 since we will be updating tooltips to the spec that we require and you can always provide your own appearance using `TUI_HINT_OPTIONS`. For example add `'my-dark'` as appearance and then add this to global styles:
```css
[tuiTheme='dark'] [data-appearance='my-dark'] {
    color: var(--tui-text-primary);
    background: var(--tui-background-elevation-3);
}
```

**Closed by waterplea** 2024-09-19 12:21 UTC
Labels: bug, state: need triage
