### ISSUE TITLE
🚀 - `InputTime` support higher input times than 23:59

### ISSUE THREAD

**Issue by 0xphilipp** [taiga-family/taiga-ui#270] opened 2021-03-06 13:25 UTC
# 🚀 Feature request

Support Input Time with higher value than 23:59. It would be great if the max value could be specified. Then the control can also be used to select a time range like in X hours, Y minutes (50 hours, 30 minutes)
Or even a different control like TuiInputTimeRange.

**Comment by nsbarsukov** [comment] 2021-11-02 14:28
Our internal teams also requires `min`/`max` input props for this input

**Comment by waterplea** [comment] 2022-01-21 09:21
The linked issue https://github.com/Tinkoff/taiga-ui/issues/1229 is probably going to be fixed under this ticket, but I'll keep it open and separate just in case.

**Comment by waterplea** [comment] 2023-03-26 10:11
I believe the issue is fixed now, however I'll keep this ticket open for 3 reasons:

1. No mention of `min`/`max` on the API page
2. Arrow navigation is still limited to 24 hours and 60 minutes/seconds
3. It needs to be revisited with new mask

**Comment by shatanov** [comment] 2023-07-25 18:45
is this issues relevant? Is it possible to try to take his?

**Closed** 2024-11-05 14:08 UTC
Labels: feature, P2
