### ISSUE TITLE
🐞 - flashing default styles in onDark/onLight mode

### ISSUE THREAD

**Issue by em-sargsyan** [taiga-family/taiga-ui#6428] opened 2024-01-11 10:15 UTC
### Playground Link

https://stackblitz.com/edit/angular-qi5ckx-adrxhe

### Description

Default styles of secondary button and marker icon are flashing in onDark/onLight mode
Can be reproduced - https://stackblitz.com/edit/angular-qi5ckx-adrxhe

### Angular version

12.2.17

### Taiga UI version

3.61.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment] 2024-01-16 11:20
Looks like it does not reproduce with experimental buttons and new approach to themes. Probably we will have to sit this one out and it will be fixed for everybody in 4.0.

**Closed by waterplea** 2024-01-16 11:20 UTC
Labels: bug, P3, S3
