### ISSUE TITLE
🐞 - Links to documentation do not work

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#8490] opened 2024-08-13 08:14 UTC
### Playground Link

taiga-ui.dev

### Description

Works as expected:
`https://taiga-ui.dev/v3/components/input-tag`

But

`https://taiga-ui.dev/v3/components/input-tag#async`
redirected to `https://taiga-ui.dev/v3/` why?

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment] 2024-08-13 12:10
This issue is caused by this lines
https://github.com/taiga-family/taiga-ui/blob/5a1e0c04b2b37382335c1c4a5fa13b884b0c61e5/projects/addon-doc/components/navigation/navigation.component.ts#L252-L259

**Comment by nsbarsukov** [comment] 2024-08-13 15:15
# Problem reasons

I've debugged the problem with [enableTracing](https://angular.dev/api/router/ExtraOptions#enableTracing).

## Case 1. URL without any hash
Opening of this page
https://taiga-ui.dev/v3/components/input-tag
produces the following logs:
 
<img width="1009" alt="Снимок экрана 2024-08-13 в 17 59 10" src="https://github.com/user-attachments/assets/98af9983-1ae3-4537-b37b-96bdb9cee5ac">

> **Pay attention** that despite the fact that url contains `v3`-segment, the router ignores it and resolves everything correctly.

## Case 2. Url with hash
Opening of this page
https://taiga-ui.dev/v3/components/input-tag#mask
triggers the following code lines:
https://github.com/taiga-family/taiga-ui/blob/5a1e0c04b2b37382335c1c4a5fa13b884b0c61e5/projects/addon-doc/components/navigation/navigation.component.ts#L252-L259
and the final logs are following ones:
<img width="1009" alt="Снимок экрана 2024-08-13 в 18 02 47" src="https://github.com/user-attachments/assets/a7748ce0-f615-40cb-b9a7-35c9dbafceef">

**Pay attention** that now routing logs contains `v3` segments. It causes problems on `RoutesRecognized` step. Routing does not know what to do with it because `baseHref` is not equal to  `v3`
 https://github.com/taiga-family/taiga-ui/blob/62cab023352d50d7237b78ac62c68256cfdd8ba3/projects/demo/project.json#L47
and it just redirects it to the root.
https://github.com/taiga-family/taiga-ui/blob/62cab023352d50d7237b78ac62c68256cfdd8ba3/projects/demo/src/modules/app/app.routes.ts#L2064-L2067


## Possible solutions 
1. Wait for Angular 18 and its feature "redirect as function" https://angular.dev/guide/routing/common-router-tasks#setting-up-redirects
2. Rewrite all infrastructure without using `baseHref: './'` (and use explicit `/v2`, `/v3` etc). It will not be easy because there are a lot of logic depends on it (for example screenshot testing uses snapshots)
3. Just add flag to `@taiga-ui/addon-doc` for possibility disable these lines for `v3` (anchor scrolling will be work but without shaking animation).
4. Revert the shaking animations without usage of `:target` pseudo-class
https://github.com/taiga-family/taiga-ui/blob/62cab023352d50d7237b78ac62c68256cfdd8ba3/projects/addon-doc/components/example/example.style.less#L9-L11

**Comment by nsbarsukov** [comment] 2024-08-15 07:58
Closed by https://github.com/taiga-family/taiga-ui/pull/8526

**Closed by nsbarsukov** 2024-08-15 07:58 UTC
Labels: bug, documentation, P3
