### ISSUE TITLE
🐞 - calendar-range does not mark checked item from range if items with equal range periods

### ISSUE THREAD

**Issue by 0ReC0** [taiga-family/taiga-ui#7781] opened 2024-06-17 10:32 UTC
### Playground Link

https://stackblitz.com/edit/angular-edlp9k?file=src%2Fapp%2Fapp.component.ts

### Description

calendar-range component, if "from range" same in two items, you cannot select the second item in order from top to bottom
For example:
it is April 14
by business logic month = beginning of month - today(April 14)
by business logic current quarter = beginning of April - today(April 14)

In stackblitz try to click to "Такой же период" to reproduce problem

### Angular version

17.1.4

### Taiga UI version

3.77.0/ (3.83.0 stackblitz)

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment] 2024-06-17 17:52
Duplicate of #7550

**Comment by mdlufy** [comment] 2024-06-17 18:59
> Duplicate

No, that's another problem

**Comment by mdlufy** [comment] 2024-06-17 19:02
> calendar-range component, if "from range" same in two items, you cannot select the second item in order from top to bottom

Yes, there is such a problem, because now the current active period is determined solely by dates and in the case of two identical periods there will be a collision

**Closed** 2024-06-21 11:21 UTC
Labels: bug, state: need triage
