### ISSUE TITLE
[BUG] No padding applied on adaptive group of buttons

### ISSUE THREAD

**Issue by kdaniel21** [taiga-family/taiga-ui#482] opened 2021-06-11 15:37 UTC
# 🐞 Bug report

### Description
The problem is that the even though the buttons do wrap inside the group, no padding is applied. It works just fine with Chrome, yet not with Firefox.

### Reproduction

https://angular-36iw7e.stackblitz.io/

### Expected behavior

It should keep the padding (or as far as I've seen in the source code, the button height).

### Versions

-   OS: Ubuntu 20.04
-   Browser: Chrome 87 & Firefox Developer Edition 90
-   Angular 12.0.1
-   Package: 2.9.1

**Comment by waterplea** [comment] 2022-01-21 07:17
@kdaniel21 the reproduction link looks the same to me in Chrome and Firefox. Can you post a screenshot of how it is supposed to look like and what you are seeing in Firefox?

**Comment by waterplea** [comment] 2022-02-25 16:48
Closing due to lack of reproduction. Feel free to reopen if needed.

**Closed by waterplea** 2022-02-25 16:48 UTC
Labels: bug, wontfix

**Comment by kdaniel21** [comment] 2022-06-18 06:16
@waterplea Excuse me, I've just noticed your message - apparently GitHub does not send emails about mentions. :disappointed: 

Looking at it, the behavior seems to be consistent across the browsers, so I'm not sure what I originally meant (maybe Chrome 87 was different?). Still, I'm pretty sure I considered the following behavior as a bug since no vertical padding is applied. At this point, I'm in two minds whether this is the intended behavior.
![Screen Shot 2022-06-18 at 08 05 23](https://user-images.githubusercontent.com/39854385/174425273-b8202c02-9995-498f-9168-123b5b213b71.png)

If this is indeed a bug, feel free to reopen it (or I can open another issue as well), else sorry for wasting your time!
Also, thanks for your work on the library, unfortunately I'm not using it actively anymore, but it was pretty cool.
